### YamlMime:ManagedReference
items:
- uid: Tide.Ork.Models.Settings
  commentId: T:Tide.Ork.Models.Settings
  id: Settings
  parent: Tide.Ork.Models
  children:
  - Tide.Ork.Models.Settings.EmailClient
  - Tide.Ork.Models.Settings.Endpoints
  - Tide.Ork.Models.Settings.Instance
  - Tide.Ork.Models.Settings.Memory
  langs:
  - csharp
  - vb
  name: Settings
  nameWithType: Settings
  fullName: Tide.Ork.Models.Settings
  type: Class
  source:
    remote:
      path: Tide/Tide.Ork/Models/Settings.cs
      branch: master
      repo: https://github.com/tide-foundation/Tide-Protocol.git
    id: Settings
    path: ../../Tide.Ork/Models/Settings.cs
    startLine: 5
  assemblies:
  - Tide.Ork
  namespace: Tide.Ork.Models
  syntax:
    content: public class Settings
    content.vb: Public Class Settings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Tide.Ork.Models.Settings.Instance
  commentId: P:Tide.Ork.Models.Settings.Instance
  id: Instance
  parent: Tide.Ork.Models.Settings
  langs:
  - csharp
  - vb
  name: Instance
  nameWithType: Settings.Instance
  fullName: Tide.Ork.Models.Settings.Instance
  type: Property
  source:
    remote:
      path: Tide/Tide.Ork/Models/Settings.cs
      branch: master
      repo: https://github.com/tide-foundation/Tide-Protocol.git
    id: Instance
    path: ../../Tide.Ork/Models/Settings.cs
    startLine: 7
  assemblies:
  - Tide.Ork
  namespace: Tide.Ork.Models
  syntax:
    content: public Instance Instance { get; set; }
    parameters: []
    return:
      type: Tide.Ork.Models.Instance
    content.vb: Public Property Instance As Instance
  overload: Tide.Ork.Models.Settings.Instance*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Tide.Ork.Models.Settings.Endpoints
  commentId: P:Tide.Ork.Models.Settings.Endpoints
  id: Endpoints
  parent: Tide.Ork.Models.Settings
  langs:
  - csharp
  - vb
  name: Endpoints
  nameWithType: Settings.Endpoints
  fullName: Tide.Ork.Models.Settings.Endpoints
  type: Property
  source:
    remote:
      path: Tide/Tide.Ork/Models/Settings.cs
      branch: master
      repo: https://github.com/tide-foundation/Tide-Protocol.git
    id: Endpoints
    path: ../../Tide.Ork/Models/Settings.cs
    startLine: 8
  assemblies:
  - Tide.Ork
  namespace: Tide.Ork.Models
  syntax:
    content: public Endpoints Endpoints { get; set; }
    parameters: []
    return:
      type: Tide.Ork.Models.Endpoints
    content.vb: Public Property Endpoints As Endpoints
  overload: Tide.Ork.Models.Settings.Endpoints*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Tide.Ork.Models.Settings.EmailClient
  commentId: P:Tide.Ork.Models.Settings.EmailClient
  id: EmailClient
  parent: Tide.Ork.Models.Settings
  langs:
  - csharp
  - vb
  name: EmailClient
  nameWithType: Settings.EmailClient
  fullName: Tide.Ork.Models.Settings.EmailClient
  type: Property
  source:
    remote:
      path: Tide/Tide.Ork/Models/Settings.cs
      branch: master
      repo: https://github.com/tide-foundation/Tide-Protocol.git
    id: EmailClient
    path: ../../Tide.Ork/Models/Settings.cs
    startLine: 9
  assemblies:
  - Tide.Ork
  namespace: Tide.Ork.Models
  syntax:
    content: public EmailClient EmailClient { get; set; }
    parameters: []
    return:
      type: Tide.Ork.Models.EmailClient
    content.vb: Public Property EmailClient As EmailClient
  overload: Tide.Ork.Models.Settings.EmailClient*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Tide.Ork.Models.Settings.Memory
  commentId: P:Tide.Ork.Models.Settings.Memory
  id: Memory
  parent: Tide.Ork.Models.Settings
  langs:
  - csharp
  - vb
  name: Memory
  nameWithType: Settings.Memory
  fullName: Tide.Ork.Models.Settings.Memory
  type: Property
  source:
    remote:
      path: Tide/Tide.Ork/Models/Settings.cs
      branch: master
      repo: https://github.com/tide-foundation/Tide-Protocol.git
    id: Memory
    path: ../../Tide.Ork/Models/Settings.cs
    startLine: 10
  assemblies:
  - Tide.Ork
  namespace: Tide.Ork.Models
  syntax:
    content: public bool Memory { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property Memory As Boolean
  overload: Tide.Ork.Models.Settings.Memory*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Tide.Ork.Models
  commentId: N:Tide.Ork.Models
  name: Tide.Ork.Models
  nameWithType: Tide.Ork.Models
  fullName: Tide.Ork.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Tide.Ork.Models.Settings.Instance*
  commentId: Overload:Tide.Ork.Models.Settings.Instance
  name: Instance
  nameWithType: Settings.Instance
  fullName: Tide.Ork.Models.Settings.Instance
- uid: Tide.Ork.Models.Instance
  commentId: T:Tide.Ork.Models.Instance
  parent: Tide.Ork.Models
  name: Instance
  nameWithType: Instance
  fullName: Tide.Ork.Models.Instance
- uid: Tide.Ork.Models.Settings.Endpoints*
  commentId: Overload:Tide.Ork.Models.Settings.Endpoints
  name: Endpoints
  nameWithType: Settings.Endpoints
  fullName: Tide.Ork.Models.Settings.Endpoints
- uid: Tide.Ork.Models.Endpoints
  commentId: T:Tide.Ork.Models.Endpoints
  parent: Tide.Ork.Models
  name: Endpoints
  nameWithType: Endpoints
  fullName: Tide.Ork.Models.Endpoints
- uid: Tide.Ork.Models.Settings.EmailClient*
  commentId: Overload:Tide.Ork.Models.Settings.EmailClient
  name: EmailClient
  nameWithType: Settings.EmailClient
  fullName: Tide.Ork.Models.Settings.EmailClient
- uid: Tide.Ork.Models.EmailClient
  commentId: T:Tide.Ork.Models.EmailClient
  parent: Tide.Ork.Models
  name: EmailClient
  nameWithType: EmailClient
  fullName: Tide.Ork.Models.EmailClient
- uid: Tide.Ork.Models.Settings.Memory*
  commentId: Overload:Tide.Ork.Models.Settings.Memory
  name: Memory
  nameWithType: Settings.Memory
  fullName: Tide.Ork.Models.Settings.Memory
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
