### YamlMime:ManagedReference
items:
- uid: Tide.Ork.Classes.OrkConfig
  commentId: T:Tide.Ork.Classes.OrkConfig
  id: OrkConfig
  parent: Tide.Ork.Classes
  children:
  - Tide.Ork.Classes.OrkConfig.#ctor(Tide.Ork.Models.Settings)
  - Tide.Ork.Classes.OrkConfig.Guid
  - Tide.Ork.Classes.OrkConfig.Id
  - Tide.Ork.Classes.OrkConfig.PrivateKey
  langs:
  - csharp
  - vb
  name: OrkConfig
  nameWithType: OrkConfig
  fullName: Tide.Ork.Classes.OrkConfig
  type: Class
  source:
    remote:
      path: Tide/Tide.Ork/Classes/OrkConfig.cs
      branch: master
      repo: https://github.com/tide-foundation/Tide-Protocol.git
    id: OrkConfig
    path: ../../Tide.Ork/Classes/OrkConfig.cs
    startLine: 7
  assemblies:
  - Tide.Ork
  namespace: Tide.Ork.Classes
  syntax:
    content: public class OrkConfig
    content.vb: Public Class OrkConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Tide.Ork.Classes.OrkConfig.PrivateKey
  commentId: P:Tide.Ork.Classes.OrkConfig.PrivateKey
  id: PrivateKey
  parent: Tide.Ork.Classes.OrkConfig
  langs:
  - csharp
  - vb
  name: PrivateKey
  nameWithType: OrkConfig.PrivateKey
  fullName: Tide.Ork.Classes.OrkConfig.PrivateKey
  type: Property
  source:
    remote:
      path: Tide/Tide.Ork/Classes/OrkConfig.cs
      branch: master
      repo: https://github.com/tide-foundation/Tide-Protocol.git
    id: PrivateKey
    path: ../../Tide.Ork/Classes/OrkConfig.cs
    startLine: 10
  assemblies:
  - Tide.Ork
  namespace: Tide.Ork.Classes
  syntax:
    content: public C25519Key PrivateKey { get; }
    parameters: []
    return:
      type: Tide.Encryption.Ecc.C25519Key
    content.vb: Public ReadOnly Property PrivateKey As C25519Key
  overload: Tide.Ork.Classes.OrkConfig.PrivateKey*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Tide.Ork.Classes.OrkConfig.Id
  commentId: P:Tide.Ork.Classes.OrkConfig.Id
  id: Id
  parent: Tide.Ork.Classes.OrkConfig
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: OrkConfig.Id
  fullName: Tide.Ork.Classes.OrkConfig.Id
  type: Property
  source:
    remote:
      path: Tide/Tide.Ork/Classes/OrkConfig.cs
      branch: master
      repo: https://github.com/tide-foundation/Tide-Protocol.git
    id: Id
    path: ../../Tide.Ork/Classes/OrkConfig.cs
    startLine: 12
  assemblies:
  - Tide.Ork
  namespace: Tide.Ork.Classes
  syntax:
    content: public BigInteger Id { get; }
    parameters: []
    return:
      type: System.Numerics.BigInteger
    content.vb: Public ReadOnly Property Id As BigInteger
  overload: Tide.Ork.Classes.OrkConfig.Id*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Tide.Ork.Classes.OrkConfig.Guid
  commentId: P:Tide.Ork.Classes.OrkConfig.Guid
  id: Guid
  parent: Tide.Ork.Classes.OrkConfig
  langs:
  - csharp
  - vb
  name: Guid
  nameWithType: OrkConfig.Guid
  fullName: Tide.Ork.Classes.OrkConfig.Guid
  type: Property
  source:
    remote:
      path: Tide/Tide.Ork/Classes/OrkConfig.cs
      branch: master
      repo: https://github.com/tide-foundation/Tide-Protocol.git
    id: Guid
    path: ../../Tide.Ork/Classes/OrkConfig.cs
    startLine: 14
  assemblies:
  - Tide.Ork
  namespace: Tide.Ork.Classes
  syntax:
    content: public Guid Guid { get; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public ReadOnly Property Guid As Guid
  overload: Tide.Ork.Classes.OrkConfig.Guid*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Tide.Ork.Classes.OrkConfig.#ctor(Tide.Ork.Models.Settings)
  commentId: M:Tide.Ork.Classes.OrkConfig.#ctor(Tide.Ork.Models.Settings)
  id: '#ctor(Tide.Ork.Models.Settings)'
  parent: Tide.Ork.Classes.OrkConfig
  langs:
  - csharp
  - vb
  name: OrkConfig(Settings)
  nameWithType: OrkConfig.OrkConfig(Settings)
  fullName: Tide.Ork.Classes.OrkConfig.OrkConfig(Tide.Ork.Models.Settings)
  type: Constructor
  source:
    remote:
      path: Tide/Tide.Ork/Classes/OrkConfig.cs
      branch: master
      repo: https://github.com/tide-foundation/Tide-Protocol.git
    id: .ctor
    path: ../../Tide.Ork/Classes/OrkConfig.cs
    startLine: 16
  assemblies:
  - Tide.Ork
  namespace: Tide.Ork.Classes
  syntax:
    content: public OrkConfig(Settings settings)
    parameters:
    - id: settings
      type: Tide.Ork.Models.Settings
    content.vb: Public Sub New(settings As Settings)
  overload: Tide.Ork.Classes.OrkConfig.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Tide.Ork.Classes
  commentId: N:Tide.Ork.Classes
  name: Tide.Ork.Classes
  nameWithType: Tide.Ork.Classes
  fullName: Tide.Ork.Classes
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Tide.Ork.Classes.OrkConfig.PrivateKey*
  commentId: Overload:Tide.Ork.Classes.OrkConfig.PrivateKey
  name: PrivateKey
  nameWithType: OrkConfig.PrivateKey
  fullName: Tide.Ork.Classes.OrkConfig.PrivateKey
- uid: Tide.Encryption.Ecc.C25519Key
  commentId: T:Tide.Encryption.Ecc.C25519Key
  parent: Tide.Encryption.Ecc
  isExternal: true
  name: C25519Key
  nameWithType: C25519Key
  fullName: Tide.Encryption.Ecc.C25519Key
- uid: Tide.Encryption.Ecc
  commentId: N:Tide.Encryption.Ecc
  isExternal: true
  name: Tide.Encryption.Ecc
  nameWithType: Tide.Encryption.Ecc
  fullName: Tide.Encryption.Ecc
- uid: Tide.Ork.Classes.OrkConfig.Id*
  commentId: Overload:Tide.Ork.Classes.OrkConfig.Id
  name: Id
  nameWithType: OrkConfig.Id
  fullName: Tide.Ork.Classes.OrkConfig.Id
- uid: System.Numerics.BigInteger
  commentId: T:System.Numerics.BigInteger
  parent: System.Numerics
  isExternal: true
  name: BigInteger
  nameWithType: BigInteger
  fullName: System.Numerics.BigInteger
- uid: System.Numerics
  commentId: N:System.Numerics
  isExternal: true
  name: System.Numerics
  nameWithType: System.Numerics
  fullName: System.Numerics
- uid: Tide.Ork.Classes.OrkConfig.Guid*
  commentId: Overload:Tide.Ork.Classes.OrkConfig.Guid
  name: Guid
  nameWithType: OrkConfig.Guid
  fullName: Tide.Ork.Classes.OrkConfig.Guid
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: Tide.Ork.Classes.OrkConfig.#ctor*
  commentId: Overload:Tide.Ork.Classes.OrkConfig.#ctor
  name: OrkConfig
  nameWithType: OrkConfig.OrkConfig
  fullName: Tide.Ork.Classes.OrkConfig.OrkConfig
- uid: Tide.Ork.Models.Settings
  commentId: T:Tide.Ork.Models.Settings
  parent: Tide.Ork.Models
  name: Settings
  nameWithType: Settings
  fullName: Tide.Ork.Models.Settings
- uid: Tide.Ork.Models
  commentId: N:Tide.Ork.Models
  name: Tide.Ork.Models
  nameWithType: Tide.Ork.Models
  fullName: Tide.Ork.Models
