@startuml auditTrailFlow
skinparam monochrome true

title AuditTrail

actor Client
participant Orks
participant Simulator
database BlockChain

...5 minutes later...
Client -> Orks: Login(tranid, username, password)

hnote over Orks: isSuccessful = verify()
Orks -> Orks: storeLogs(tranid, username,\n isSuccessful, timestamp)
Orks --> Client: isSuccessful

alt totalMinutes mod 5 == 0

Orks --> Simulator: audit(orkid, logs)

hnote over Simulator
  cnt = count(groupLogsBy(tranid, isSuccessful))
  wasSuccessful = cnt >= thershold
end note

Simulator --> BlockChain: store(tranid, username,\n wasSuccessful, timestamp)

end
@enduml