@startuml silentLoginJwtFlow
skinparam monochrome true

title Silent Login JWT Flow

note over Client
c = {
  ...
  homeOrk: ork1
  ...
}
end note


Client -> TideButton: new TideButton(c)
activate Client
activate TideButton
TideButton -> Enclave: OpenEnclave()
activate Enclave

note over Enclave
silentJwt = localStorage.get(silentJwt)
end note
alt silentJwt != null ?
note over Enclave
vendorJwt = GenerateVendorJwt(silentJwt)
end note
  Enclave->TideButton:OK(vendorJwt)
    else
  Enclave -> Tide: Login()
  activate Tide
Tide -> Enclave: Success(cvk)
deactivate Tide
note over Enclave
vendorJwt = GenerateVendorJwt(cvk)
silentJwt = GenerateSilentLoginJwt(cvk)
localStorage.set(silentJwt)
end note
  Enclave->TideButton:OK(vendorJwt)
  deactivate Enclave
end

TideButton -> Client:OK(vendorJwt)
deactivate TideButton
deactivate Client
@enduml