@startuml throttlingClass
skinparam monochrome true

title Throttling
class "Blacklist" as black
class "ThrottleAttribute" as attr <<middleware>>
class "ThrottlingManager" as manager
class "RequestCache" as cache

black - attr
attr - manager
manager -- cache

class black {
  +lapse: TimeSpan
  +elements: MemoryCache
  +add(id)
  +exists(id): bool
}

class attr {
  +param: string
  +onActionExecution(context, next)
}

class manager {
  +lapse: TimeSpan
  +allow: ushort 
  +elements: MemoryCache
  +throttle(id): bool
  +remove(id)
}

class cache {
  +times: int
  +start: datetime 
}
@enduml
