version: '3.4'

services: 
  db_host:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        SA_PASSWORD: 'P@ssw0rd'
        ACCEPT_EULA: 'Y'
    networks:
      - 'simulator'

  db_migration:
    build:
      context: .
      dockerfile: ./Tide.Simulator/migration.Dockerfile
    environment:
      SA_PASSWORD: 'P@ssw0rd'
      SA_HOST: 'db_host'
    depends_on:
      - 'db_host'
    networks:
      - 'simulator'

  simulator:
    build:
      context: .
      dockerfile: ./Tide.Simulator/Dockerfile
    command: ['./wait-for-it.sh', 'db_migration:80', '-s', '-t', '30',  '--', 'dotnet', 'Tide.Simulator.dll']
    environment:
      VIRTUAL_HOST: 'simulator.local'
      Settings__BearerKey: '5Fs4D8rzmI6eUur3zbw27ZeQ'
      Settings__Connection: 'Server=db_host;Database=db;User Id=sa;Password=P@ssw0rd;'
      Settings__Threshold: '3'
    depends_on:
      - 'db_host'
      - 'db_migration'
    networks: 
      - 'simulator'
      - 'default'

  vendor:
    build:
      context: .
      dockerfile: ./Tide.Vendor/Dockerfile
    command: [ './wait-for-it.sh', 'simulator:80', '-s', '-t', '30', '--', 'dotnet', 'Tide.Vendor.dll' ]
    environment:
      Settings__Keys__PrivateKey: 'DHZzxQp+d0F7UokwkOuwy9YQmVxhR1IB34cOVXPVdX0PQeA43Y3ax9ebpVUTr3KiRYaykD7f6M9mzPPapCOjpieF5z2LLukWRXK4J3Ay0bZE85/VCjJT9HrbeLItSKiS'
      Settings__Keys__SecretKey: 'AhAtBR+XCacnLUJjJ7e7C7yvIE/I1kYZ1lOFa0Hn8G+oKmUoj8R2AeNDAqD57cm2NG9F'
      Settings__OrkUrls__0: 'http://ork1.local'
      Settings__OrkUrls__1: 'http://ork2.local'
      Settings__OrkUrls__2: 'http://ork3.local'
    depends_on:
      - ork1
      - ork2
      - ork3
    networks: 
      - 'default'

  ork1:
    build:
      context: .
      dockerfile: ./Tide.Ork/Dockerfile
    ports:
      - '5001:80'
    command: [ './wait-for-it.sh', 'simulator:80', '-s', '-t', '30', '--', 'dotnet', 'Tide.Ork.dll', '--register', 'http://ork1.local']
    environment:
      VIRTUAL_HOST: 'ork1.local'
      Settings__Endpoints__Simulator__Api: 'http://simulator:80/simulator'
      Settings__Endpoints__Simulator__Password: 'Password'
      Settings__Instance__PrivateKey: 'CBHaP68zFuCHJHMpoNatSi1Ea43nJD2aN4hzznfRaF9epxsm/Ly4U1koay26BJ2KYbUBXTwV5sG7XbJh8Fi/e3AO1S+fr9VPSm8oG2TIQZdntg7V50hkYj5pt/SsLsL3'
      Settings__Instance__SecretKey: 'AhDaAyMV+S5kqDA2GcNC1u9RIPFA0470RdxjEuEKjHhBgCQrsqR2Ik81gcSd06wIWoDH'
      Settings__Instance__Username: 'ork1'
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
    depends_on:
      - 'simulator'
    networks:
      default:
        aliases:
          - ork1.local

  ork2:
    build:
      context: .
      dockerfile: ./Tide.Ork/Dockerfile
    ports:
      - '5002:80'
    command: [ './wait-for-it.sh', 'simulator:80', '-s', '-t', '30', '--', 'dotnet', 'Tide.Ork.dll', '--register', 'http://ork2.local']
    environment:
      VIRTUAL_HOST: 'ork2.local'
      Settings__Endpoints__Simulator__Api: 'http://simulator:80/simulator'
      Settings__Endpoints__Simulator__Password: 'Password'
      Settings__Instance__PrivateKey: 'AOb+bNal/0M0bT4jFC0K6+YuEBwwR5nBMaps7kZR64JFKCrU63/BQWasFCgIlgtlSOv5jzQfMjFBfsud/veC0ljtUScANNgwqmitEl6ChDOSyWBzA57sFmWAX2pe8fGR'
      Settings__Instance__SecretKey: 'AhC9OpCHalVMzgDc8LAyky05IKY92xhE2SmmCJ1RgzC0hkgDMkVa8W0cdsB0/I/1hW7D'
      Settings__Instance__Username: 'ork2'
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
    depends_on:
      - 'simulator'
    networks:
      default:
        aliases:
          - ork2.local

  ork3:
    build:
      context: .
      dockerfile: ./Tide.Ork/Dockerfile
    ports:
      - '5003:80'
    command: [ './wait-for-it.sh', 'simulator:80', '-s', '-t', '30', '--', 'dotnet', 'Tide.Ork.dll', '--register', 'http://ork3.local']
    environment:
      VIRTUAL_HOST: 'ork3.local'
      Settings__Endpoints__Simulator__Api: 'http://simulator:80/simulator'
      Settings__Endpoints__Simulator__Password: 'Password'
      Settings__Instance__PrivateKey: 'BZJrKMczqmkPfk1ACDFP/kvyxczUFNbgwIf4SMPW0WMf0vePtGU88MW25xtujo+1oF1XODIJ7DlJigcZTDBPbAtMkH6YU2CzcO3eG9K0YCkLY8j98ahpdNzf/DBHH2NI'
      Settings__Instance__SecretKey: 'AhAsCWVibFkZUZyT6XkcaPi8IB4+NnKWF1vE9zemMgW09pCY3OgLZAmbZ/WsxVD5g3Jb'
      Settings__Instance__Username: 'ork3'
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
    depends_on:
      - 'simulator'
    networks:
      default:
        aliases:
          - ork3.local

networks:
  simulator:
    driver: bridge