// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Tide.Simulator.Migrations {
    [DbContext(typeof(BlockchainContext))]
    internal class BlockchainContextModelSnapshot : ModelSnapshot {
        protected override void BuildModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tide.Simulator.Models.Account", b => {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Hash")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Salt")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Token")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Username")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Account");
            });

            modelBuilder.Entity("Tide.Simulator.Models.BlockData", b => {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int>("Contract")
                    .HasColumnType("int");

                b.Property<string>("Data")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset>("DateCreated")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("Index")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Scope")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("Stale")
                    .HasColumnType("bit");

                b.Property<int>("Table")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Data");
            });
#pragma warning restore 612, 618
        }
    }
}